### ISSUE TITLE
Add Oracle CodeOne 2019

### ISSUE THREAD

**Issue by ederks85** [softwaremill/it-cfp-list#108]
Hello,

I would like to add Oracle CodeOne 2019 to the list, but I am not yet authorized to push to this repository and create a pull request for it. Is this correct and if so, could you please grant me access?

Kind regards,

Edwin Derks

**Comment by mmatloka** [comment]
Hello,
You should be able to create branch on the fork of the repository, and then to create a pull request here providing this branch.
